version: '3.8'
services:

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd0
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ENABLE_V2=true
    ports:
      - "2379:2379"
    networks:
      - patroni_net

  patroni1:
    image: ghcr.io/zalando/spilo-15:3.0-p1
    container_name: patroni1
    volumes:
      - ./patroni/patroni1.yml:/config/patroni.yml
    environment:
      - PATRONI_CONFIG_FILE=/config/patroni.yml
      - ETCD_HOSTS=etcd:2379
      - PATRONI_NAME=patroni1
    ports:
      - "5433:5432"
      - "8001:8008"
    networks:
      - patroni_net
    depends_on:
      - etcd

  patroni2:
    image: ghcr.io/zalando/spilo-15:3.0-p1
    container_name: patroni2
    volumes:
      - ./patroni/patroni2.yml:/config/patroni.yml
    environment:
      - PATRONI_CONFIG_FILE=/config/patroni.yml
      - ETCD_HOSTS=etcd:2379
      - PATRONI_NAME=patroni2
    ports:
      - "5434:5432"
      - "8002:8008"
    networks:
      - patroni_net
    depends_on:
      - etcd

  patroni3:
    image: ghcr.io/zalando/spilo-15:3.0-p1
    container_name: patroni3
    volumes:
      - ./patroni/patroni3.yml:/config/patroni.yml
    environment:
      - PATRONI_CONFIG_FILE=/config/patroni.yml
      - ETCD_HOSTS=etcd:2379
      - PATRONI_NAME=patroni3
    ports:
      - "5435:5432"
      - "8003:8008"
    networks:
      - patroni_net
    depends_on:
      - etcd

networks:
  patroni_net:
    driver: bridge

